# model:
#   arch: minigptp
#   model_type: pretrain
#   max_txt_len: 1024
#   image_size: 448
#   end_sym: "</s>"
#   llama_model: "Llama-2-7b-chat-hf"
#   ckpt: "checkpoints/checkpoint_stage3.pth"
#   use_grad_checkpoint: True
#   chat_template: True
#   lora_r: 64
#   lora_alpha: 16

# datasets:
# MSD_pancreas_ref:
#     batch_size: 6
#     vis_processor:
#       train:
#         name: "blip2_image_train"
#         image_size: 448
#     text_processor:
#       train:
#         name: "blip_caption"
#     sample_ratio: 50

#   #TCIA_pancreas_ref:
#   #  batch_size: 6
#   #  vis_processor:
#   #    train:
#   #      name: "blip2_image_train"
#   #      image_size: 448
#   #  text_processor:
#   #    train:
#   #      name: "blip_caption"
#   #  sample_ratio: 50

# run:
#   task: image_text_pretrain
#   # optimizer
#   lr_sched: "linear_warmup_cosine_lr"
#   init_lr: 1e-5
#   min_lr: 1e-6
#   warmup_lr: 1e-6

#   weight_decay: 0.05
#   max_epoch: 50
#   num_workers: 6
#   warmup_steps: 1000
#   iters_per_epoch: 1000

#   seed: 42
#   output_dir: "checkpoints/pancreas_detection"

#   amp: True
#   resume_ckpt_path: null

#   evaluate: False 
#   train_splits: ["train"]

#   device: "cuda"
#   world_size: 1
#   dist_url: "env://"
#   distributed: True

#   wandb_log: True
#   job_name: minigptv2_finetune

# export PYTHONPATH="/home/sj/MiniGPT/minigpt4:$PYTHONPATH"
# export CUDA_VISIBLE_DEVICES=3
model:
  arch: minigpt_v2
  model_type: pretrain
  vit_model: "swin_unetr" # !! 关键修改 !!
  max_txt_len: 1024
  image_size: 96 # 这里的尺寸现在对应3D patch的尺寸
  end_sym: "</s>"
  llama_model: "Llama-2-7b-chat-hf"
  ckpt: "/home/sj/MiniGPT-Pancreas/checkpoints/checkpoint_stage3.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  MSD_pancreas_ref_3d: # !! 关键修改：使用新的3D dataset !!
    batch_size: 2      # !! 关键修改：减小batch size !!
    vis_processor:
      train:
        name: "pancreas_3d_train" # !! 关键修改：使用新的3D processor !!
        patch_size: 96
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 100 # 如果只有一个数据集，设为100

run:
  task: image_text_pretrain
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6
  weight_decay: 0.05
  max_epoch: 50
  num_workers: 4 # 根据你的CPU调整
  warmup_steps: 1000
  iters_per_epoch: 1000
  seed: 42
  output_dir: "/home/sj/MiniGPT/checkpoints/pancreas_detection" # 新的输出目录
  amp: True
  resume_ckpt_path: null
  evaluate: False 
  train_splits: ["train"]
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  wandb_log: False
  job_name: minigptv2_finetune_3d
